
def gv

pipeline {
    agent any
    tools {
        maven 'Maven'
    }

    parameters {
        string(name:'VERSION', defaultValue:'', description:'version to deploy on prod')
        choice(name:'VERSION', choices:['1.1.0','1.2.0','1.3.0'], description:'')
        booleanParam(name:'executeTest', defaultValue: true, description:'')
    }

    environment{
       branchName = 'develop'
    }

    stages {

        stage("init") {
            steps {
                script {
                   gv = load "script.groovy" 
                }
            }
        }

        stage('Build') {
            steps {

                script {
                    gv.buildApp()
                }

                 echo "building branch ${branchName}"
                 sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {

            when {
                expression {
                    params.executeTest == true
                }
            }
            steps {
                script {
                    gv.testApp()
                }
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                
                script {
                    gv.deployApp()
                }

                sh 'chmod +x ./jenkins/scripts/deliver.sh'
            }
        }
    }
}